name: reusable workflow test

on:
  issues:
    types: [opened, reopened, closed]

permissions: {}

jobs:
  jobs:
    uses: jsnerdic/reusable-workflows/workflows/messageAction.yaml@main
    permissions:
      issues: write
