name: reusable workflow test

on:
  issues:
    types: [opened, reopened, closed]

jobs:
  test:
    uses: jsnerdic/reusable-workflows/.github/workflows/messageAction.yaml@main
    permissions:
      contents: read
      issues: write
    with:
      message: 'Hello World'
