name: reusable workflow test

on:
  issues:
    types: [opened, reopened, closed]

jobs:
  test:
    uses: jsnerdic/reusable-workflows/workflows/messageAction.yaml@main
    permissions:
      issues: write
