name: reusable workflow test

on:
  issues:
    types: [opened, reopened, closed]

jobs:
  job1:
    uses: jsnerdic/reusable-workflows/.github/workflows/dataTransfer.yaml@main
    permissions:
      contents: read
      issues: write
    with:
      count: 1
  job2:
    needs: job1
    uses: jsnerdic/reusable-workflows/.github/workflows/dataTransfer.yaml@main
    permissions:
      contents: read
      issues: write
    with:
      count: ${{ needs.job1.outputs.countTransfer }}
