name: reusable workflow test

on:
  issues:
    types: [opened, reopened, closed]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Test
        uses: jsnerdic/reusable-workflows/.github/workflows/messageAction.yaml@main
        with:
          message: 'Hello World'
      - name: Set output
        id: set_output
        run: echo ${{ steps.Test.outputs.OUTPUT_TEST }}
