name: reusable workflow test

on:
  issues:
    types: [opened, reopened, closed]

jobs:
  test:
    uses: jsnerdic/reusable-workflows/.github/workflows/messageAction.yaml@main
    permissions:
      contents: read
      issues: write
    with:
      message: 'Hello World'
  test2:
    needs: [test]
    uses: jsnerdic/reusable-workflows/.github/workflows/messageAction.yaml@main
    permissions:
      contents: read
      issues: write
    with:
      message: ${{ needs.test.outputs.OUTPUT_TEST }}
  test3:
    needs: [test2]
    uses: jsnerdic/reusable-workflows/.github/workflows/messageAction.yaml@main
    permissions:
      contents: read
      issues: write
    with:
      message: ${{ needs.test2.outputs.OUTPUT_TEST }}
